
# seo stuff
url: "https://yangyangoceanographer.github.io/"
title: "Yang Yang | Physical Oceanographer"
description: "My personal site"

disqus_shortname: Yang Yang | Physical Oceanographer
permalink: /:year/:title.html
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
